### ISSUE TITLE
benchmark presentation

### ISSUE THREAD

**Issue by afgiel** [DVation-VMWare/vmware#18]
it seems like you needed something to do for this project and it seems you were very interested in the competitive landscape so you should make a benchmarking presentation to the group - maybe for Tuesday or later this week

this presentation should answer the following questions: 
- for each of the competitors - what makes them stand out? what is their value prop?
- what features are ubiquitous for the space? (all products offer them)
-  for each of our proposed features what is the feature in the competition that is most similar? 

looking forward to hearing it

**Comment by jsajnani79** [comment]
sounds good. @hkader are you still interested in doing a bit of this as well? there are enough players to divide up
