### ISSUE TITLE
update your member page on the squarespace 

### ISSUE THREAD

**Issue by afgiel** [DVation-VMWare/vmware#2]
@sseira @jnecamp @jsajnani79 @hkader

update your member page on the squarespace to be more complete and comprehensive 

add whatever you want to it just make sure it is updated in some way

**Comment by afgiel** [comment]
if you need the login and password message me, I dont want to post it here

**Comment by afgiel** [comment]
mine is updated

**Comment by sseira** [comment]
sour cream and DONEions

**Comment by afgiel** [comment]
@jnecamp @jsajnani79 pls do this even if very simple

**Comment by jsajnani79** [comment]
updated mine a while back

On Sun, Feb 22, 2015 at 1:35 PM, Andrew Giel notifications@github.com
wrote:

> @jnecamp https://github.com/jnecamp @jsajnani79
> https://github.com/jsajnani79 pls do this even if very simple
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DVation-VMWare/vmware/issues/2#issuecomment-75461554.

## 

Jai Sajnani
Stanford University | Class of 2015
Electrical Engineering, Computer Science
President | Stanford IEEE
jsajnani79@gmail.com
(516) 808-9183 (C)

**Comment by afgiel** [comment]
oh my bad

**Comment by jnecamp** [comment]
sorry about the delay
