### ISSUE TITLE
update wiki to have link to squarespace 

### ISSUE THREAD

**Issue by afgiel** [DVation-VMWare/vmware#6]
idk if you want to remove everything on there (probably not) but at least note that we have a blog up and running and supply a link

**Comment by jnecamp** [comment]
Added link to blog to team wiki... we should start moving all of our team information to the squarespace site and start phasing out the wiki page

**Comment by afgiel** [comment]
I say we remove the blurb at the beginning of the wiki, keep our pictures, and maybe remove some of the stuff after our pictures. Once you do that close the issue :shipit:

**Comment by jnecamp** [comment]
Done!
