### ISSUE TITLE
follow up with Todd Dayton regarding meeting 2/16-2/18

### ISSUE THREAD

**Issue by afgiel** [DVation-VMWare/vmware#7]
I am the only one the filled out the when2meet

we need to prototype and show a lot of different idea to different people 

@jnecamp @jsajnani79 @hkader

**Comment by jnecamp** [comment]
Filled out when2meet

**Comment by hkader** [comment]
filled out when2meet

**Comment by sseira** [comment]
so I was thinking that only Todd was going to fill the when2meet and we were going to accommodate his schedule. Ill send an 2nd email though
